### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by ssmith353** [metal/metal-charts#2]
I don't see metal-charts published to npm. Would it be possible to add it? 

Thanks!

**Comment by Robert-Frampton** [comment]
Hey @ssmith353 

Since this project is technically a WIP we haven't published to npm yet. We would need to have proper documentation by then as well.

If you're hoping to try it out anyways, it's technically possible to load this dependency straight from github.

```bash
npm i --save metal/metal-charts
```

Though I definitely do not recommend you actually use this in a production setting.

Hope that helps!

**Comment by jbalsas** [comment]
Hey @ssmith353, we have published a `1.0.0-alpha.0` but be aware that API changes are to be expected. This is still in a very early development stage. We will be working through the next weeks to add the documentation @Robert-Frampton mentions.

**Comment by ssmith353** [comment]
@jbalsas, this is awesome! Thanks!
